language: objective-c  # force osx for now.

os:
  - osx
#   # - linux

before_install:
  - brew update
  - brew tap optimizers/cutest
  - brew install cutest
  - brew install mastsif
  - export ARCHDEFS="$(brew --prefix)/Cellar/archdefs/0.1/libexec"
  - export CUTEST="$(brew --prefix)/Cellar/cutest/0.2/libexec"
  - export SIFEDECODE="$(brew --prefix)/Cellar/sifdecode/0.3/libexec"
  - export MASTSIF="$(brew --prefix)/opt/mastsif/share/mastsif"
  - export MYARCH=mac64.osx.gfo
  - pip install -q numpy

install:
  - python setup.py install
  - python cutest/test/test_cutest.py


